---
- name: proda
  hosts: proda
  become: yes
 
  tasks:
 
  - name: install the apache2 package
    shell: sudo apt-get -y install apache2
  - name: Copy file with owner and permissions
    copy:
      src: /home/gitfile/proda/
      dest: /var/www/html/
 
