---
- name: prodb
  hosts: prodb
  become: yes
 
  tasks:
 
  - name: install the apache2 package
    shell: sudo apt-get -y install apache2
  - name: Copy file with owner and permissions
    copy:
      src: /home/gitfile/prodb/index.html
      dest: /var/www/html/index.html
