---
- name: dev
  hosts: dev
 
  tasks:
 
  - name: install the apache2 package
    shell: sudo apt-get -y install apache2
  - name: Copy file with owner and permissions
    copy:
      src: /home/gitfile/dev/index.html
      dest: /var/www/html/index.html
