---
- name: prodb
  hosts: all
  become: yes
 
  tasks:
  - name: update
    shell: sudo apt-get update
  - name: install the apache2 package
    shell: sudo apt-get -y install apache2
  - name: Copy file with owner and permissions
    copy:
      src: /var/lib/jenkins/workspace/browser/prodb/
      dest: /var/www/html/
